name: Weather App
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: run deploy.sh
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_APP_AUTHORIZATION_KEY: ${{secrets.VITE_APP_AUTHORIZATION_KEY}}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_NAME: ${{ secrets.USER_NAME}}
        run: npm install && npm run deploy
          

